# Generated by Django 4.1.6 on 2023-03-19 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_applicationquestiontext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='DateofBirth',
            field=models.DateField(default=datetime.datetime(2023, 3, 19, 10, 38, 52, 406570, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='customuser',
            name='RealName',
            field=models.CharField(default='John Doe', max_length=50),
            preserve_default=False,
        ),
    ]
