# Generated by Django 4.1.6 on 2023-03-19 10:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customuser_dateofbirth_customuser_realname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='PornName',
            field=models.CharField(default='Eski Monmo', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='DateofBirth',
            field=models.DateField(default=datetime.datetime(2023, 3, 19, 10, 47, 13, 725162, tzinfo=datetime.timezone.utc)),
        ),
    ]
