# Generated by Django 4.1.6 on 2023-03-19 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_applicationquestiontext_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='DateofBirth',
            field=models.DateField(default=datetime.datetime(2023, 3, 19, 10, 59, 11, 533994, tzinfo=datetime.timezone.utc)),
        ),
    ]
