# Generated by Django 4.1.6 on 2023-03-19 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_applicationquestiontext_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationquestiontrueorfalse',
            name='user',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='DateofBirth',
            field=models.DateField(default=datetime.datetime(2023, 3, 19, 11, 3, 39, 798225, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='ApplicationQuestionText',
        ),
        migrations.DeleteModel(
            name='ApplicationQuestionTrueOrFalse',
        ),
    ]
