# Generated by Django 4.1.6 on 2023-03-19 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_customuser_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='DateofBirth',
            field=models.DateField(default=datetime.datetime(2023, 3, 19, 11, 9, 50, 755950, tzinfo=datetime.timezone.utc)),
        ),
    ]
