# Generated by Django 4.1.6 on 2023-03-21 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_applicationquestiontext_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='DateofBirth',
            field=models.DateField(default=datetime.datetime(2023, 3, 21, 13, 57, 52, 857227, tzinfo=datetime.timezone.utc)),
        ),
    ]
