# Generated by Django 4.1.6 on 2023-03-21 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_customuser_dateofbirth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='DateofBirth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
