# Generated by Django 4.1.6 on 2023-03-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_customuser_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profileImage',
            field=models.ImageField(default='image.jpg', upload_to='profilePic'),
            preserve_default=False,
        ),
    ]
