# Generated by Django 4.1.6 on 2023-03-29 18:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_customuser_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1ans', models.CharField(max_length=40)),
                ('question2ans', models.CharField(max_length=200)),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='applicationquestiontrueorfalse',
            name='user',
        ),
        migrations.DeleteModel(
            name='ApplicationQuestionText',
        ),
        migrations.DeleteModel(
            name='ApplicationQuestionTrueOrFalse',
        ),
    ]
