# Generated by Django 4.1.6 on 2023-03-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_applications_delete_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profileImage',
            field=models.ImageField(default='image.jpg', upload_to='profilePic'),
        ),
    ]
